### ISSUE TITLE
JS Version seems to provide different results than online version

### ISSUE THREAD

**Issue by ndom91** [MakeNowJust-Labo/recheck#61]
Hey so I'm trying to write a little CLI around this where a user can pass in a glob pattern of files to be matched, and it will find the files, loop over the lines in said files to find regexes, and finally test those against this checker.

So far so good, everything is working - however I can't get it to come up with a positive match although I've verified two results in my test file should trigger a positive (i.e. "vulnerable") match.

Here's my two test regexes and the output of running `check(testRegex)` on them:

```js
1. /^([a-zA-Z0-9-_@]+|\.\/)+\.(png|jpg|jpeg|pdf)$/m
{
  source: '/^([a-zA-Z0-9-_@]+|\\.\\/)+\\.(png|jpg|jpeg|pdf)$/m',
  flags: '',
  status: 'safe',
  checker: 'automaton',
  complexity: { type: 'linear', summary: 'linear', isFuzz: false }
}

2. /^(a|a)*$/
{
  source: '/^(a|a)*$/',
  flags: '',
  status: 'safe',
  checker: 'automaton',
  complexity: { type: 'linear', summary: 'linear', isFuzz: false }
}
```

I see on the first one in "source" it seems to have done some escaping of the backslashes itself, but I pasted both the escaped and unescaped version into your online checker, and they both came back vulnerable every single time, no matter which checker I used (fuzz or automaton). 

Do I need to set any flags or anything in the second parameter of the `check()` function? I didn't see any examples of flags or anything that could be set there.

Thanks for this cool checker!

**Comment by MakeNowJust** [comment]
Pass the `source` string as the first argument of `check` and `flags` as the second. For example,

```javascript
const { check } = require('@makenowjust-labo/recheck');

const regex = /^([a-zA-Z0-9-_@]+|\.\/)+\.(png|jpg|jpeg|pdf)$/m
check(regex.source, reges.flags);
```

And the third argument is a configuration for analysis (e.g. `timeout`, `checker`).

**Comment by ndom91** [comment]
Ah okay, so without the `/` at the front or back and the "flags" in the second argument are the flags from the input regex - now I understand. I thought the argument was for some unknown flags that could be passed to `check()` haha.

Anyway, the regex seems to now "fail" correctly. Thanks!

**Comment by ndom91** [comment]
@MakeNowJust fyi - my cli package based on your library here is up! Well, the first working version is out haha.

It's on npm, so users can run it via `npx ...` and i'm using `vercel/pkg` to generate statically linked binaries, available under github releases for macos, linux and windows.

https://github.com/ndom91/recheck-cli

Thanks!
